[tool.ruff]
line-length = 79
target-version = "py39"

[tool.ruff.format]
quote-style = "preserve"
docstring-code-format = true

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "S", "U"]
ignore = [
    # we only use asserts for type narrowing
    "S101",
    # this is client tool running on a user's own system: users can open
    # whatever urls they want to
    "S310",
    # ditto for running executables via subprocess
    "S603",
    # we make extensive use of printf style formatting and rewriting is a chore
    "UP031",
]
